#!/usr/bin/env python
import sys
import numpy as np
import ctypes as ct
import time
import argparse
# Hacky parser/reader for values written in Futhark syntax.  Used for
# reading stdin when compiling standalone programs with the Python
# code generator.

import numpy as np
import string
import struct
import sys

lookahead_buffer = []

def reset_lookahead():
    global lookahead_buffer
    lookahead_buffer = []

def get_char(f):
    global lookahead_buffer
    if len(lookahead_buffer) == 0:
        return f.read(1)
    else:
        c = lookahead_buffer[0]
        lookahead_buffer = lookahead_buffer[1:]
        return c

def get_chars(f, n):
    s = b''
    for _ in range(n):
        s += get_char(f)
    return s

def unget_char(f, c):
    global lookahead_buffer
    lookahead_buffer = [c] + lookahead_buffer

def peek_char(f):
    c = get_char(f)
    if c:
        unget_char(f, c)
    return c

def skip_spaces(f):
    c = get_char(f)
    while c != None:
        if c.isspace():
            c = get_char(f)
        elif c == b'-':
          # May be line comment.
          if peek_char(f) == b'-':
            # Yes, line comment. Skip to end of line.
            while (c != b'\n' and c != None):
              c = get_char(f)
          else:
            break
        else:
          break
    if c:
        unget_char(f, c)

def parse_specific_char(f, expected):
    got = get_char(f)
    if got != expected:
        unget_char(f, got)
        raise ValueError
    return True

def parse_specific_string(f, s):
    # This funky mess is intended, and is caused by the fact that if `type(b) ==
    # bytes` then `type(b[0]) == int`, but we need to match each element with a
    # `bytes`, so therefore we make each character an array element
    b = s.encode('utf8')
    bs = [b[i:i+1] for i in range(len(b))]
    for c in bs:
        parse_specific_char(f, c)
    return True

def optional(p, *args):
    try:
        return p(*args)
    except ValueError:
        return None

def optional_specific_string(f, s):
    c = peek_char(f)
    # This funky mess is intended, and is caused by the fact that if `type(b) ==
    # bytes` then `type(b[0]) == int`, but we need to match each element with a
    # `bytes`, so therefore we make each character an array element
    b = s.encode('utf8')
    bs = [b[i:i+1] for i in range(len(b))]
    if c == bs[0]:
        return parse_specific_string(f, s)
    else:
        return False

def sepBy(p, sep, *args):
    elems = []
    x = optional(p, *args)
    if x != None:
        elems += [x]
        while optional(sep, *args) != None:
            x = p(*args)
            elems += [x]
    return elems

# Assumes '0x' has already been read
def parse_hex_int(f):
    s = b''
    c = get_char(f)
    while c != None:
        if c in string.hexdigits:
            s += c
            c = get_char(f)
        elif c == '_':
            c = get_char(f) # skip _
        else:
            unget_char(f, c)
            break
    return str(int(s, 16))


def parse_int(f):
    s = b''
    c = get_char(f)
    if c == b'0' and peek_char(f) in [b'x', b'X']:
        c = get_char(f) # skip X
        s += parse_hex_int(f)
    else:
        while c != None:
            if c.isdigit():
                s += c
                c = get_char(f)
            elif c == '_':
                c = get_char(f) # skip _
            else:
                unget_char(f, c)
                break
    if len(s) == 0:
        raise ValueError
    return s

def parse_int_signed(f):
    s = b''
    c = get_char(f)

    if c == b'-' and peek_char(f).isdigit():
      s = c + parse_int(f)
    else:
      if c != b'+':
          unget_char(f, c)
      s = parse_int(f)

    return s

def read_str_comma(f):
    skip_spaces(f)
    parse_specific_char(f, b',')
    return b','

def read_str_int(f, s):
    skip_spaces(f)
    x = int(parse_int_signed(f))
    optional_specific_string(f, s)
    return x

def read_str_uint(f, s):
    skip_spaces(f)
    x = int(parse_int(f))
    optional_specific_string(f, s)
    return x

def read_str_i8(f):
    return read_str_int(f, 'i8')
def read_str_i16(f):
    return read_str_int(f, 'i16')
def read_str_i32(f):
    return read_str_int(f, 'i32')
def read_str_i64(f):
    return read_str_int(f, 'i64')

def read_str_u8(f):
    return read_str_int(f, 'u8')
def read_str_u16(f):
    return read_str_int(f, 'u16')
def read_str_u32(f):
    return read_str_int(f, 'u32')
def read_str_u64(f):
    return read_str_int(f, 'u64')

def read_char(f):
    skip_spaces(f)
    parse_specific_char(f, b'\'')
    c = get_char(f)
    parse_specific_char(f, b'\'')
    return c

def read_str_hex_float(f, sign):
    int_part = parse_hex_int(f)
    parse_specific_char(f, b'.')
    frac_part = parse_hex_int(f)
    parse_specific_char(f, b'p')
    exponent = parse_int(f)

    int_val = int(int_part, 16)
    frac_val = float(int(frac_part, 16)) / (16 ** len(frac_part))
    exp_val = int(exponent)

    total_val = (int_val + frac_val) * (2.0 ** exp_val)
    if sign == b'-':
        total_val = -1 * total_val

    return float(total_val)


def read_str_decimal(f):
    skip_spaces(f)
    c = get_char(f)
    if (c == b'-'):
      sign = b'-'
    else:
      unget_char(f,c)
      sign = b''

    # Check for hexadecimal float
    c = get_char(f)
    if (c == '0' and (peek_char(f) in ['x', 'X'])):
        get_char(f)
        return read_str_hex_float(f, sign)
    else:
        unget_char(f, c)

    bef = optional(parse_int, f)
    if bef == None:
        bef = b'0'
        parse_specific_char(f, b'.')
        aft = parse_int(f)
    elif optional(parse_specific_char, f, b'.'):
        aft = parse_int(f)
    else:
        aft = b'0'
    if (optional(parse_specific_char, f, b'E') or
        optional(parse_specific_char, f, b'e')):
        expt = parse_int_signed(f)
    else:
        expt = b'0'
    return float(sign + bef + b'.' + aft + b'E' + expt)

def read_str_f32(f):
    x = read_str_decimal(f)
    optional_specific_string(f, 'f32')
    return x

def read_str_f64(f):
    x = read_str_decimal(f)
    optional_specific_string(f, 'f64')
    return x

def read_str_bool(f):
    skip_spaces(f)
    if peek_char(f) == b't':
        parse_specific_string(f, 'true')
        return True
    elif peek_char(f) == b'f':
        parse_specific_string(f, 'false')
        return False
    else:
        raise ValueError

def read_str_empty_array(f, type_name, rank):
    parse_specific_string(f, 'empty')
    parse_specific_char(f, b'(')
    for i in range(rank):
        parse_specific_string(f, '[]')
    parse_specific_string(f, type_name)
    parse_specific_char(f, b')')

    return None

def read_str_array_elems(f, elem_reader, type_name, rank):
    skip_spaces(f)
    try:
        parse_specific_char(f, b'[')
    except ValueError:
        return read_str_empty_array(f, type_name, rank)
    else:
        xs = sepBy(elem_reader, read_str_comma, f)
        skip_spaces(f)
        parse_specific_char(f, b']')
        return xs

def read_str_array_helper(f, elem_reader, type_name, rank):
    def nested_row_reader(_):
        return read_str_array_helper(f, elem_reader, type_name, rank-1)
    if rank == 1:
        row_reader = elem_reader
    else:
        row_reader = nested_row_reader
    return read_str_array_elems(f, row_reader, type_name, rank-1)

def expected_array_dims(l, rank):
  if rank > 1:
      n = len(l)
      if n == 0:
          elem = []
      else:
          elem = l[0]
      return [n] + expected_array_dims(elem, rank-1)
  else:
      return [len(l)]

def verify_array_dims(l, dims):
    if dims[0] != len(l):
        raise ValueError
    if len(dims) > 1:
        for x in l:
            verify_array_dims(x, dims[1:])

def read_str_array(f, elem_reader, type_name, rank, bt):
    elems = read_str_array_helper(f, elem_reader, type_name, rank)
    if elems == None:
        # Empty array
        return np.empty([0]*rank, dtype=bt)
    else:
        dims = expected_array_dims(elems, rank)
        verify_array_dims(elems, dims)
        return np.array(elems, dtype=bt)

################################################################################

READ_BINARY_VERSION = 2

# struct format specified at
# https://docs.python.org/2/library/struct.html#format-characters

FUTHARK_INT8 = 0
FUTHARK_INT16 = 1
FUTHARK_INT32 = 2
FUTHARK_INT64 = 3
FUTHARK_UINT8 = 4
FUTHARK_UINT16 = 5
FUTHARK_UINT32 = 6
FUTHARK_UINT64 = 7
FUTHARK_FLOAT32 = 8
FUTHARK_FLOAT64 = 9
FUTHARK_BOOL = 10

def mk_bin_scalar_reader(t):
    def bin_reader(f):
        fmt = FUTHARK_PRIMTYPES[t]['bin_format']
        size = FUTHARK_PRIMTYPES[t]['size']
        return struct.unpack('<' + fmt, get_chars(f, size))[0]
    return bin_reader

read_bin_i8 = mk_bin_scalar_reader(FUTHARK_INT8)
read_bin_i16 = mk_bin_scalar_reader(FUTHARK_INT16)
read_bin_i32 = mk_bin_scalar_reader(FUTHARK_INT32)
read_bin_i64 = mk_bin_scalar_reader(FUTHARK_INT64)

read_bin_u8 = mk_bin_scalar_reader(FUTHARK_UINT8)
read_bin_u16 = mk_bin_scalar_reader(FUTHARK_UINT16)
read_bin_u32 = mk_bin_scalar_reader(FUTHARK_UINT32)
read_bin_u64 = mk_bin_scalar_reader(FUTHARK_UINT64)

read_bin_f32 = mk_bin_scalar_reader(FUTHARK_FLOAT32)
read_bin_f64 = mk_bin_scalar_reader(FUTHARK_FLOAT64)

read_bin_bool = mk_bin_scalar_reader(FUTHARK_BOOL)

def read_is_binary(f):
    skip_spaces(f)
    c = get_char(f)
    if c == b'b':
        bin_version = read_bin_u8(f)
        if bin_version != READ_BINARY_VERSION:
            panic(1, "binary-input: File uses version %i, but I only understand version %i.\n",
                  bin_version, READ_BINARY_VERSION)
        return True
    else:
        unget_char(f, c)
        return False

FUTHARK_PRIMTYPES = {}
FUTHARK_PRIMTYPES[FUTHARK_INT8] = \
    {'binname' : b"  i8",
     'type_name' : "i8",
     'size' : 1,
     'bin_reader': read_bin_i8,
     'str_reader': read_str_i8,
     'bin_format': 'b'
    }
FUTHARK_PRIMTYPES[FUTHARK_INT16]   = \
    {'binname' : b" i16",
     'type_name' : "i16",
     'size' : 2,
     'bin_reader': read_bin_i16,
     'str_reader': read_str_i16,
     'bin_format': 'h'
    }
FUTHARK_PRIMTYPES[FUTHARK_INT32]   = \
    {'binname' : b" i32",
     'type_name' : "i32",
     'size' : 4,
     'bin_reader': read_bin_i32,
     'str_reader': read_str_i32,
     'bin_format': 'i'
    }
FUTHARK_PRIMTYPES[FUTHARK_INT64]   = \
    {'binname' : b" i64",
     'type_name' : "i64",
     'size' : 8,
     'bin_reader': read_bin_i64,
     'str_reader': read_str_i64,
     'bin_format': 'q'
    }

FUTHARK_PRIMTYPES[FUTHARK_UINT8] = \
    {'binname' : b"  u8",
     'type_name' : "u8",
     'size' : 1,
     'bin_reader': read_bin_u8,
     'str_reader': read_str_u8,
     'bin_format': 'B'
    }
FUTHARK_PRIMTYPES[FUTHARK_UINT16]   = \
    {'binname' : b" u16",
     'type_name' : "u16",
     'size' : 2,
     'bin_reader': read_bin_u16,
     'str_reader': read_str_u16,
     'bin_format': 'H'
    }
FUTHARK_PRIMTYPES[FUTHARK_UINT32]   = \
    {'binname' : b" u32",
     'type_name' : "u32",
     'size' : 4,
     'bin_reader': read_bin_u32,
     'str_reader': read_str_u32,
     'bin_format': 'I'
    }
FUTHARK_PRIMTYPES[FUTHARK_UINT64]   = \
    {'binname' : b" u64",
     'type_name' : "u64",
     'size' : 8,
     'bin_reader': read_bin_u64,
     'str_reader': read_str_u64,
     'bin_format': 'Q'
    }

FUTHARK_PRIMTYPES[FUTHARK_FLOAT32] = \
    {'binname' : b" f32",
     'type_name' : "f32",
     'size' : 4,
     'bin_reader': read_bin_f32,
     'str_reader': read_str_f32,
     'bin_format': 'f'
    }
FUTHARK_PRIMTYPES[FUTHARK_FLOAT64] = \
    {'binname' : b" f64",
     'type_name' : "f64",
     'size' : 8,
     'bin_reader': read_bin_f64,
     'str_reader': read_str_f64,
     'bin_format': 'd'
    }
FUTHARK_PRIMTYPES[FUTHARK_BOOL]    = \
    {'binname' : b"bool",
     'type_name' : "bool",
     'size' : 1,
     'bin_reader': read_bin_bool,
     'str_reader': read_str_bool,
     'bin_format': 'b'
    }

def read_bin_read_type_enum(f):
    read_binname = get_chars(f, 4)

    for (k,v) in FUTHARK_PRIMTYPES.items():
        if v['binname'] == read_binname:
            return k
    panic(1, "binary-input: Did not recognize the type '%s'.\n", read_binname)

def read_bin_ensure_scalar(f, expected_type):
  dims = read_bin_i8(f)

  if dims != 0:
      panic(1, "binary-input: Expected scalar (0 dimensions), but got array with %i dimensions.\n", dims)

  bin_type_enum = read_bin_read_type_enum(f)
  if bin_type_enum != expected_type:
      panic(1, "binary-input: Expected scalar of type %s but got scalar of type %s.\n",
            FUTHARK_PRIMTYPES[expected_type]['type_name'],
            FUTHARK_PRIMTYPES[bin_type_enum]['type_name'])

# ------------------------------------------------------------------------------
# General interface for reading Primitive Futhark Values
# ------------------------------------------------------------------------------

def read_general(f, ty):
    if read_is_binary(f):
        read_bin_ensure_scalar(f, ty)
        return FUTHARK_PRIMTYPES[ty]['bin_reader'](f)
    return FUTHARK_PRIMTYPES[ty]['str_reader'](f)

def read_i8(f):
    return read_general(f, FUTHARK_INT8)

def read_i16(f):
    return read_general(f, FUTHARK_INT16)

def read_i32(f):
    return read_general(f, FUTHARK_INT32)

def read_i64(f):
    return read_general(f, FUTHARK_INT64)

def read_u8(f):
    return read_general(f, FUTHARK_UINT8)

def read_u16(f):
    return read_general(f, FUTHARK_UINT16)

def read_u32(f):
    return read_general(f, FUTHARK_UINT32)

def read_u64(f):
    return read_general(f, FUTHARK_UINT64)

def read_f32(f):
    return read_general(f, FUTHARK_FLOAT32)

def read_f64(f):
    return read_general(f, FUTHARK_FLOAT64)

def read_bool(f):
    return read_general(f, FUTHARK_BOOL)

def read_array(f, expected_type, rank, ctype):
    if not read_is_binary(f):
        str_reader = FUTHARK_PRIMTYPES[expected_type]['str_reader']
        return read_str_array(f, str_reader, FUTHARK_PRIMTYPES[expected_type]['type_name'], rank, ctype)

    bin_rank = read_bin_u8(f)

    if bin_rank != rank:
        panic(1, "binary-input: Expected %i dimensions, but got array with %i dimensions.\n",
              rank, bin_rank)

    bin_type_enum = read_bin_read_type_enum(f)
    if expected_type != bin_type_enum:
        panic(1, "binary-input: Expected %iD-array with element type '%s' but got %iD-array with element type '%s'.\n",
              rank, FUTHARK_PRIMTYPES[expected_type]['type_name'],
              rank, FUTHARK_PRIMTYPES[bin_type_enum]['type_name'])

    shape = []
    elem_count = 1
    for i in range(rank):
        bin_size = read_bin_u64(f)
        elem_count *= bin_size
        shape.append(bin_size)

    bin_fmt = FUTHARK_PRIMTYPES[bin_type_enum]['bin_format']

    arr = np.fromfile(f, dtype='<'+bin_fmt, count=elem_count, sep='')
    arr.shape = shape

    return arr

if sys.version_info >= (3,0):
    input_stream = sys.stdin.buffer
else:
    input_stream = sys.stdin

################################################################################
### end of reader.py
################################################################################
# Helper functions dealing with memory blocks.

import ctypes as ct

def addressOffset(x, offset, bt):
  return ct.cast(ct.addressof(x.contents)+int(offset), ct.POINTER(bt))

def allocateMem(size):
  return ct.cast((ct.c_byte * max(0,size))(), ct.POINTER(ct.c_byte))

# Copy an array if its is not-None.  This is important for treating
# Numpy arrays as flat memory, but has some overhead.
def normaliseArray(x):
  if (x.base is x) or (x.base is None):
    return x
  else:
    return x.copy()

def unwrapArray(x):
  return normaliseArray(x).ctypes.data_as(ct.POINTER(ct.c_byte))

def createArray(x, dim):
  return np.ctypeslib.as_array(x, shape=dim)

def indexArray(x, offset, bt, nptype):
  return nptype(addressOffset(x, offset, bt)[0])

def writeScalarArray(x, offset, v):
  ct.memmove(ct.addressof(x.contents)+int(offset), ct.addressof(v), ct.sizeof(v))

# An opaque Futhark value.
class opaque(object):
  def __init__(self, desc, *payload):
    self.data = payload
    self.desc = desc

  def __repr__(self):
    return "<opaque Futhark value of type {}>".format(self.desc)
def panic(exitcode, fmt, *args):
    sys.stderr.write('%s: ' % sys.argv[0])
    sys.stderr.write(fmt % args)
    sys.exit(exitcode)
# Scalar functions.

import numpy as np
import struct

def signed(x):
  if type(x) == np.uint8:
    return np.int8(x)
  elif type(x) == np.uint16:
    return np.int16(x)
  elif type(x) == np.uint32:
    return np.int32(x)
  else:
    return np.int64(x)

def unsigned(x):
  if type(x) == np.int8:
    return np.uint8(x)
  elif type(x) == np.int16:
    return np.uint16(x)
  elif type(x) == np.int32:
    return np.uint32(x)
  else:
    return np.uint64(x)

def shlN(x,y):
  return x << y

def ashrN(x,y):
  return x >> y

def sdivN(x,y):
  return x // y

def smodN(x,y):
  return x % y

def udivN(x,y):
  return signed(unsigned(x) // unsigned(y))

def umodN(x,y):
  return signed(unsigned(x) % unsigned(y))

def squotN(x,y):
  return np.int32(float(x) / float(y))

def sremN(x,y):
  return np.fmod(x,y)

def sminN(x,y):
  return min(x,y)

def smaxN(x,y):
  return max(x,y)

def uminN(x,y):
  return signed(min(unsigned(x),unsigned(y)))

def umaxN(x,y):
  return signed(max(unsigned(x),unsigned(y)))

def fminN(x,y):
  return min(x,y)

def fmaxN(x,y):
  return max(x,y)

def powN(x,y):
  return x ** y

def fpowN(x,y):
  return x ** y

def sleN(x,y):
  return x <= y

def sltN(x,y):
  return x < y

def uleN(x,y):
  return unsigned(x) <= unsigned(y)

def ultN(x,y):
  return unsigned(x) < unsigned(y)

def lshr8(x,y):
  return np.int8(np.uint8(x) >> np.uint8(y))

def lshr16(x,y):
  return np.int16(np.uint16(x) >> np.uint16(y))

def lshr32(x,y):
  return np.int32(np.uint32(x) >> np.uint32(y))

def lshr64(x,y):
  return np.int64(np.uint64(x) >> np.uint64(y))

def sext_T_i8(x):
  return np.int8(x)

def sext_T_i16(x):
  return np.int16(x)

def sext_T_i32(x):
  return np.int32(x)

def sext_T_i64(x):
  return np.int32(x)

def zext_i8_i8(x):
  return np.int8(np.uint8(x))

def zext_i8_i16(x):
  return np.int16(np.uint8(x))

def zext_i8_i32(x):
  return np.int32(np.uint8(x))

def zext_i8_i64(x):
  return np.int64(np.uint8(x))

def zext_i16_i8(x):
  return np.int8(np.uint16(x))

def zext_i16_i16(x):
  return np.int16(np.uint16(x))

def zext_i16_i32(x):
  return np.int32(np.uint16(x))

def zext_i16_i64(x):
  return np.int64(np.uint16(x))

def zext_i32_i8(x):
  return np.int8(np.uint32(x))

def zext_i32_i16(x):
  return np.int16(np.uint32(x))

def zext_i32_i32(x):
  return np.int32(np.uint32(x))

def zext_i32_i64(x):
  return np.int64(np.uint32(x))

def zext_i64_i8(x):
  return np.int8(np.uint64(x))

def zext_i64_i16(x):
  return np.int16(np.uint64(x))

def zext_i64_i32(x):
  return np.int32(np.uint64(x))

def zext_i64_i64(x):
  return np.int64(np.uint64(x))

shl8 = shl16 = shl32 = shl64 = shlN
ashr8 = ashr16 = ashr32 = ashr64 = ashrN
sdiv8 = sdiv16 = sdiv32 = sdiv64 = sdivN
smod8 = smod16 = smod32 = smod64 = smodN
udiv8 = udiv16 = udiv32 = udiv64 = udivN
umod8 = umod16 = umod32 = umod64 = umodN
squot8 = squot16 = squot32 = squot64 = squotN
srem8 = srem16 = srem32 = srem64 = sremN
smax8 = smax16 = smax32 = smax64 = smaxN
smin8 = smin16 = smin32 = smin64 = sminN
umax8 = umax16 = umax32 = umax64 = umaxN
umin8 = umin16 = umin32 = umin64 = uminN
pow8 = pow16 = pow32 = pow64 = powN
fpow32 = fpow64 = fpowN
fmax32 = fmax64 = fmaxN
fmin32 = fmin64 = fminN
sle8 = sle16 = sle32 = sle64 = sleN
slt8 = slt16 = slt32 = slt64 = sltN
ule8 = ule16 = ule32 = ule64 = uleN
ult8 = ult16 = ult32 = ult64 = ultN
sext_i8_i8 = sext_i16_i8 = sext_i32_i8 = sext_i64_i8 = sext_T_i8
sext_i8_i16 = sext_i16_i16 = sext_i32_i16 = sext_i64_i16 = sext_T_i16
sext_i8_i32 = sext_i16_i32 = sext_i32_i32 = sext_i64_i32 = sext_T_i32
sext_i8_i64 = sext_i16_i64 = sext_i32_i64 = sext_i64_i64 = sext_T_i64

def ssignum(x):
  return np.sign(x)

def usignum(x):
  if x < 0:
    return ssignum(-x)
  else:
    return ssignum(x)

def sitofp_T_f32(x):
  return np.float32(x)
sitofp_i8_f32 = sitofp_i16_f32 = sitofp_i32_f32 = sitofp_i64_f32 = sitofp_T_f32

def sitofp_T_f64(x):
  return np.float64(x)
sitofp_i8_f64 = sitofp_i16_f64 = sitofp_i32_f64 = sitofp_i64_f64 = sitofp_T_f64

def uitofp_T_f32(x):
  return np.float32(unsigned(x))
uitofp_i8_f32 = uitofp_i16_f32 = uitofp_i32_f32 = uitofp_i64_f32 = uitofp_T_f32

def uitofp_T_f64(x):
  return np.float64(unsigned(x))
uitofp_i8_f64 = uitofp_i16_f64 = uitofp_i32_f64 = uitofp_i64_f64 = uitofp_T_f64

def fptosi_T_i8(x):
  return np.int8(np.trunc(x))
fptosi_f32_i8 = fptosi_f64_i8 = fptosi_T_i8

def fptosi_T_i16(x):
  return np.int16(np.trunc(x))
fptosi_f32_i16 = fptosi_f64_i16 = fptosi_T_i16

def fptosi_T_i32(x):
  return np.int32(np.trunc(x))
fptosi_f32_i32 = fptosi_f64_i32 = fptosi_T_i32

def fptosi_T_i64(x):
  return np.int64(np.trunc(x))
fptosi_f32_i64 = fptosi_f64_i64 = fptosi_T_i64

def fptoui_T_i8(x):
  return np.uint8(np.trunc(x))
fptoui_f32_i8 = fptoui_f64_i8 = fptoui_T_i8

def fptoui_T_i16(x):
  return np.uint16(np.trunc(x))
fptoui_f32_i16 = fptoui_f64_i16 = fptoui_T_i16

def fptoui_T_i32(x):
  return np.uint32(np.trunc(x))
fptoui_f32_i32 = fptoui_f64_i32 = fptoui_T_i32

def fptoui_T_i64(x):
  return np.uint64(np.trunc(x))
fptoui_f32_i64 = fptoui_f64_i64 = fptoui_T_i64

def fpconv_f32_f64(x):
  return np.float64(x)

def fpconv_f64_f32(x):
  return np.float32(x)

def futhark_log64(x):
  return np.float64(np.log(x))

def futhark_sqrt64(x):
  return np.sqrt(x)

def futhark_exp64(x):
  return np.exp(x)

def futhark_cos64(x):
  return np.cos(x)

def futhark_sin64(x):
  return np.sin(x)

def futhark_acos64(x):
  return np.arccos(x)

def futhark_asin64(x):
  return np.arcsin(x)

def futhark_atan64(x):
  return np.arctan(x)

def futhark_atan2_64(x, y):
  return np.arctan2(x, y)

def futhark_isnan64(x):
  return np.isnan(x)

def futhark_isinf64(x):
  return np.isinf(x)

def futhark_to_bits64(x):
  s = struct.pack('>d', x)
  return np.int64(struct.unpack('>q', s)[0])

def futhark_from_bits64(x):
  s = struct.pack('>q', x)
  return np.float64(struct.unpack('>d', s)[0])

def futhark_log32(x):
  return np.float32(np.log(x))

def futhark_sqrt32(x):
  return np.float32(np.sqrt(x))

def futhark_exp32(x):
  return np.exp(x)

def futhark_cos32(x):
  return np.cos(x)

def futhark_sin32(x):
  return np.sin(x)

def futhark_acos32(x):
  return np.arccos(x)

def futhark_asin32(x):
  return np.arcsin(x)

def futhark_atan32(x):
  return np.arctan(x)

def futhark_atan2_32(x, y):
  return np.arctan2(x, y)

def futhark_isnan32(x):
  return np.isnan(x)

def futhark_isinf32(x):
  return np.isinf(x)

def futhark_to_bits32(x):
  s = struct.pack('>f', x)
  return np.int32(struct.unpack('>l', s)[0])

def futhark_from_bits32(x):
  s = struct.pack('>l', x)
  return np.float32(struct.unpack('>f', s)[0])
runtime_file = None
do_warmup_run = False
num_runs = 1
entry_point = "main"
parser = argparse.ArgumentParser(description="A compiled Futhark program.")
parser.add_argument("-t", "--write-runtime-to", action="append", default=[])
parser.add_argument("-r", "--runs", action="append", default=[])
parser.add_argument("-e", "--entry-point", action="append", default=[])
parser.add_argument("-b", "--binary-output", action="append_const", default=[],
                    const=None)
parser_result = vars(parser.parse_args(sys.argv[1:]))
for optarg in parser_result["write_runtime_to"]:
  if runtime_file:
    runtime_file.close()
  runtime_file = open(optarg, "w")
for optarg in parser_result["runs"]:
  num_runs = optarg
  do_warmup_run = True
for optarg in parser_result["entry_point"]:
  entry_point = optarg
for optarg in parser_result["binary_output"]:
  pass
class internal:
  def __init__(self):
    pass
  def futhark_main(self, a_mem_sizze_2497, a_mem_2498, sizze_2484):
    binop_x_2500 = sext_i32_i64(sizze_2484)
    bytes_2499 = (binop_x_2500 * np.int64(4))
    mem_2501 = allocateMem(bytes_2499)
    acc_2491 = np.int32(0)
    i_2490 = np.int32(0)
    one_2512 = np.int32(1)
    for counter_2511 in range(sizze_2484):
      binop_param_y_2488 = indexArray(a_mem_2498, (i_2490 * np.int32(4)),
                                      ct.c_int32, np.int32)
      res_2489 = (acc_2491 + binop_param_y_2488)
      writeScalarArray(mem_2501, (i_2490 * np.int32(4)), ct.c_int32(res_2489))
      row_2495 = indexArray(mem_2501, (i_2490 * np.int32(4)), ct.c_int32,
                            np.int32)
      acc_tmp_2509 = row_2495
      acc_2491 = acc_tmp_2509
      i_2490 += one_2512
    discard_2496 = acc_2491
    out_arrsizze_2508 = sizze_2484
    out_memsizze_2507 = bytes_2499
    out_mem_2506 = mem_2501
    return (out_memsizze_2507, out_mem_2506, out_arrsizze_2508)
self = internal()
def entry_main():
  a_mem_2498_ext = read_array(input_stream, FUTHARK_INT32, 1, np.int32)
  if not(((type(a_mem_2498_ext) in [np.ndarray]) and (a_mem_2498_ext.dtype == np.int32))):
    raise TypeError("Argument #0 has invalid value\nFuthark type: {}\nType of given Python value: {}\n".format("[]i32",
                                                                                                               type(a_mem_2498_ext)))
  try:
    assert (sizze_2484 == np.int32(a_mem_2498_ext.shape[0])), 'variant dimension wrong'
  except NameError as e:
    sizze_2484 = np.int32(a_mem_2498_ext.shape[0])
  a_mem_sizze_2497 = np.int32(a_mem_2498_ext.nbytes)
  a_mem_2498 = unwrapArray(a_mem_2498_ext)
  try:
    with np.errstate(divide="ignore", over="ignore", under="ignore",
                     invalid="ignore"):
      if do_warmup_run:
        a_mem_copy_2513 = allocateMem(a_mem_2498_ext.nbytes)
        ct.memmove(addressOffset(a_mem_copy_2513, 0, ct.c_byte),
                   addressOffset(a_mem_2498, 0, ct.c_byte),
                   a_mem_2498_ext.nbytes)
        (out_memsizze_2507, out_mem_2506,
         out_arrsizze_2508) = self.futhark_main(a_mem_sizze_2497,
                                                a_mem_copy_2513, sizze_2484)
      for i in range(int(num_runs)):
        a_mem_copy_2513 = allocateMem(a_mem_2498_ext.nbytes)
        ct.memmove(addressOffset(a_mem_copy_2513, 0, ct.c_byte),
                   addressOffset(a_mem_2498, 0, ct.c_byte),
                   a_mem_2498_ext.nbytes)
        time_start = time.time()
        (out_memsizze_2507, out_mem_2506,
         out_arrsizze_2508) = self.futhark_main(a_mem_sizze_2497,
                                                a_mem_copy_2513, sizze_2484)
        time_end = time.time()
        if runtime_file:
          runtime_file.write(str((int((time_end * 1000000)) - int((time_start * 1000000)))))
          runtime_file.write("\n")
  except AssertionError as e:
    sys.exit("Assertion.{} failed".format(e))
  if runtime_file:
    runtime_file.close()
  if (np.product([out_arrsizze_2508]) == 0):
    sys.stdout.write("empty(i32)")
  else:
    print_first_2515 = True
    sys.stdout.write("[")
    for print_elem_2514 in createArray(ct.cast(out_mem_2506, ct.POINTER(ct.c_int32)),
                                       (out_arrsizze_2508,)):
      if not(print_first_2515):
        sys.stdout.write(", ")
      sys.stdout.write(("%di32" % print_elem_2514))
      print_first_2515 = False
    sys.stdout.write("]")
  sys.stdout.write("\n")
entry_points = {"main": entry_main}
entry_point_fun = entry_points.get(entry_point)
if (entry_point_fun == None):
  sys.exit("No entry point '{}'.  Select another with --entry point.  Options are:\n{}".format(entry_point,
                                                                                               "\n".join(entry_points.keys())))
else:
  entry_point_fun()